### ISSUE TITLE
Fix "TODO" issue in handlers/clienthandler.go

### ISSUE THREAD

**Issue by JustAnotherOrganizationGit** [JustAnotherOrganization/tiberious#43]
TODO found

https://codeclimate.com/github/JustAnotherOrganization/tiberious/handlers/clienthandler.go#issue_57903e9973baea000105b924

**Comment by IngCr3at1on** [comment]
https://github.com/JustAnotherOrganization/tiberious/blob/master/handlers/clienthandler.go#L126

**Comment by jeremywho** [comment]
Can I claim this one?  

What is the desired behavior here? 
There is a numerical suffix getting appended to the guest username and there is a section for config.AllowGuests, so should the client be disconnected if they are a guest and AllowGuests is false?

**Comment by IngCr3at1on** [comment]
@jeremywho that's one way to go about it yes. Have to give them the opportunity to auth first though (which auth isn't really fully implemented now that I think about it). I'm actually wondering now why I tagged that one hacktoberfest cause it's not an insanely easy task....

Could lock them out of joining any rooms and send them a notification advising to auth and if they don't after a set time you kick them. Not sure; may need more discussion @GrimTheReaper thoughts?

@jeremywho otherwise yes you're more than welcome to take a crack at it if we can come up with a good method for handling it :D

**Comment by GrimTheReaper** [comment]
@IngCr3at1on I like the idea of allowing them to connect and then authenticating. That way they can auth after a connection is ensured, rather than beforehand.

**Comment by IngCr3at1on** [comment]
@GrimTheReaper that of course means spinning up a timer to kick them if they don't auth after a period of time; 2 minutes maybe?

**Comment by GrimTheReaper** [comment]
@IngCr3at1on Maybe that could be configurable? So that Admins can disable the functionality of they want to. Anyway, we should have a centralized timer at some point for timed/scheduled event processing.

**Comment by IngCr3at1on** [comment]
@GrimTheReaper yes we can make the kick time configurable (good idea considering the guest access is meant to be configurable as well).

**Comment by IngCr3at1on** [comment]
@GrimTheReaper & @jeremywho it looks like I did more work on auth then I remembered: https://github.com/JustAnotherOrganization/tiberious/blob/master/handlers/clienthandler.go#L33

**Comment by IngCr3at1on** [comment]
Though I don't like the whole part of deleting a user; I guess it makes sense though since it's a guest user that's getting deleted.

**Comment by IngCr3at1on** [comment]
Replaced with v2 branch.
